name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: [Python CI with pytest]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          docker build -t ci-cd-docker-example .
          docker run ci-cd-docker-example pytest --disable-warnings -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Docker Hub
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ./.github/workflows/deploy.yml
        with:
          DOCKHUB_USERNAME: ${{ secrets.DOCKHUB_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Notify on failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: echo 'The triggering workflow failed'

