name: Deploy

on:
  workflow_run:
    workflows: ["Python CI with pytest"]
    types: [completed]

jobs:
  on-success:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: production

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: aaryamaster/jenkins-pipeline

      - name: Build Docker image
        run: docker build -t aaryamaster/jenkins-pipeline .

      - name: Push Docker image
        run: docker push aaryamaster/jenkins-pipeline

  on-failure:
    name: Notify Failure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
